# Tema Escuro Elegante e Minimalista
[theme]
base = "dark"
primaryColor = "#3b82f6"  # Azul elegante
backgroundColor = "#0a0a0a"  # Preto profundo
secondaryBackgroundColor = "#141414"  # Cinza escuro
textColor = "#e5e5e5"  # Texto claro
font = "sans serif"

[server]
# Configurações do servidor
port = 8501
enableCORS = true
enableXsrfProtection = true
maxUploadSize = 50
headless = true

[browser]
# Configurações do navegador
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[client]
# Configurações do cliente
showErrorDetails = true
toolbarMode = "minimal"
